-- Analysis 
--  we will use fact_swiggy_orders for analysis

--            KPI's (Key Perfomance Indicator)

SELECT * FROM fact_swiggy_orders f;

-- 1. Total Orders
SELECT COUNT(*) AS total_orders
FROM fact_swiggy_orders f;
-- Total Orders Are 394806

-- 2. Total Revenue (INR Millon)
SELECT
ROUND(SUM(price_inr) / 1000000.0,2) AS Total_Revenue 
FROM fact_swiggy_orders f;
-- Total Revenue in Millon is 106.01

-- 3. Average Dish Price
SELECT 
ROUND(AVG(price_inr)) AS Average_price
FROM fact_swiggy_orders;
-- 269 is a Avergae dish price

-- 4. Average Rating
SELECT ROUND(AVG(rating)) AS Avg_Rating
FROM fact_swiggy_orders;
--  Average Rating is 4

------------------------------------------------------------
--                 GRANULAR REQUIREMENTS 

-- 1. Monthly Orders Trends
SELECT 
d.year,
d.month,
d.month_name,
COUNT(*) AS Monthly_orders
FROM dim_date AS d
JOIN fact_swiggy_orders f 
ON d.date_id = f.date_id
GROUP BY
d.year, d.month,d.month_name
ORDER BY COUNT(*) DESC;
-- january 2025 has highest orders 50786.

-- 2. Total Revenue Per months
SELECT
d.year,
d.month,
d.month_name,
ROUND(SUM(price_inr)) AS Total_Revenue_per_Month
FROM fact_swiggy_orders AS f 
JOIN dim_date AS d
ON f.date_id = d.date_id
GROUP BY d.year,d.month,d.month_name
ORDER BY SUM(price_inr) DESC;
-- january generated a highest Revenue 13647963

-- 3. Quarterly Orders Trends
SELECT 
d.year,
d.quarter,
COUNT(*) AS Quarterly_Orders
FROM dim_date AS d JOIN
fact_swiggy_orders AS f
ON d.date_id = f.date_id
GROUP BY d.year,d.quarter
ORDER BY count(*) DESC;
-- in year 2025 at quarter 2 has highest orders 148310

-- 4. Yearly Trends
SELECT
d.year,
COUNT(*) AS Yearly_orders
FROM dim_date AS d JOIN 
fact_swiggy_orders AS f 
ON d.date_id = f.date_id
GROUP BY d.year
ORDER BY COUNT(*) DESC;

-- 5. Orders by Day of Week (Mon - Sun)

SELECT
TO_CHAR(full_date, 'Day') AS day_name,
COUNT(*) AS orders_per_day
FROM dim_date AS d JOIN
fact_swiggy_orders f 
ON d.date_id = f.date_id
GROUP BY TO_CHAR(full_date, 'Day')
ORDER BY COUNT(*) DESC;
--  orders are more on Saturday and Sunday 


------------------------------------------------------------
--           LOCATION-BASED ANALYSIS
-- 1. Top 10 cities by order Volume
SELECT 
l.city,
COUNT(*) AS Order_per_city
FROM dim_location AS l 
JOIN fact_swiggy_orders AS f
ON l.location_id = f.location_id
GROUP BY
l.city
ORDER BY COUNT(*) DESC LIMIT 10;
-- from top 10 city Bengaluru is city from where more orders placed

-- 2.  Top 10 cities by Total Revenue Volume

SELECT
l.city,
SUM(f.price_inr) AS total_revenue_per_city
FROM dim_location AS l JOIN
fact_swiggy_orders AS f
ON f.location_id = l.location_id
GROUP BY
l.city
ORDER BY SUM(f.price_inr) DESC LIMIT 10;

-- 3. Revenue Contributation per state
SELECT
l.state,
SUM(f.price_inr) AS Revenue_Contri_per_state
FROM fact_swiggy_orders AS f
JOIN dim_location l
ON l.location_id = f.location_id
GROUP BY l.state
ORDER BY SUM(f.price_inr) DESC;
--  Highest Revenue Generated by karnataka

-----------------------------------------------------------
--            FOOD PERFOMANCE
-- 1. Top 10 restaurants by orders
SELECT * FROM dim_restaurant;

SELECT r.restaurant_name,
COUNT(*) AS orders_per_rest
FROM fact_swiggy_orders AS f
JOIN dim_restaurant AS r
ON f.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name
ORDER BY COUNT(*) DESC LIMIT 10;

-- 2. Top Categories(indian,Chiness etc)
SELECT * FROM dim_category;

SELECT c.category,
COUNT(*) AS top_categories_Perf
FROM fact_swiggy_orders AS f 
JOIN dim_category AS c
ON f.category_id = c.category_id
GROUP BY c.category
ORDER BY COUNT(*) DESC;


-- 3. Most ordered Dishes
SELECT * FROM dim_dish;

SELECT 
d.dish_name,
COUNT(*) AS most_ordered_dish
FROM fact_swiggy_orders AS f 
JOIN  dim_dish AS d
ON d.dish_id = f.dish_id
GROUP BY d.dish_name
ORDER BY COUNT(*) DESC;

-- 4. Cusine Perfomance(Order+ Avg Rating)

SELECT 
c.category,
COUNT(*) AS total_orders,
AVG(ROUND(f.rating)) AS avg_rating
FROM  fact_swiggy_orders AS f 
JOIN dim_category AS c ON f.category_id = c.category_id
GROUP BY c.category
ORDER BY total_orders DESC;

-----------------------------------------------------------

         -- CUSTOMER SPENDING insights
-- Total Orders by Price Range

SELECT
CASE
    WHEN price_inr < 100 THEN 'Under 100'
	WHEN price_inr BETWEEN 100 AND 199 THEN '100-199'
	WHEN price_inr BETWEEN 200 AND 299 THEN '200-299'
	WHEN price_inr BETWEEN 300 AND 499 THEN '300-499'
	ELSE '500+'
END AS price_range,
COUNT(*) AS total_orders
FROM  fact_swiggy_orders
GROUP BY
    CASE
    WHEN price_inr < 100 THEN 'Under 100'
	WHEN price_inr BETWEEN 100 AND 199 THEN '100-199'
	WHEN price_inr BETWEEN 200 AND 299 THEN '200-299'
	WHEN price_inr BETWEEN 300 AND 499 THEN '300-499'
	ELSE '500+'
END
ORDER BY total_orders DESC;


-----------------------------------------------------------
--           RATING ANALYSIS
-- 1. Distrubution of dish rating from 1-5

SELECT
d.dish_name,
COUNT(*) AS rating_count
FROM fact_swiggy_orders
GROUP BY rating
ORDER BY rating;







